---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dind-no-resources
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: image-url
      description: the url of the image to build
    - name: pipeline-debug
      default: "0"
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: properties-file
          value: ""
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: build-and-push-docker
      runAfter: [clone-repository]
      taskRef:
        name: icr-execute-in-dind
      params:
        - name: image-url
          value: $(params.image-url)
        - name: image-tag
          value: 1.0.0-$(tasks.clone-repository.results.git-branch)-$(tasks.clone-repository.results.git-commit)
        - name: properties-file
          value: ""
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: source
          workspace: pipeline-ws
