---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-dind-cluster
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: pipeline-debug
      default: "0"
  resources:
    - name: app-image
      type: image
    - name: build-cluster
      type: cluster
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: build-and-push-docker
      runAfter: [clone-repository]
      taskRef:
        name: icr-execute-in-dind-cluster
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: source
          workspace: pipeline-ws
      resources:
        inputs:
          - name: cluster
            resource: build-cluster
        outputs:
          - name: built-image
            resource: app-image
